
# -------------------------
#    DEFAULT TEMPLATE
# -------------------------

admin:
  username: admin
  password: admin

config:
  audit:
    enabled: false
  loftHost: vcluster-dev.appflex.io
accessKeys:
  - name: admin
    key: "C1QY0GBytw4BqENKWzbTUwE4FI3lyFJEREz77N6DzSjRi90AhlxFEwjwy0lO5Wit"
    user: admin
    scope:
      projects:
        - default
      resources:
        - apiGroups:
            - management.loft.sh
          resources:
            - "*"
          verbs:
            - "*"

ingress:
  enabled: true
  host: vcluster-dev.appflex.io

features:
  virtualClusters: true
  projects: true
  templates: true

projects:
  createDefault: true

virtualCluster:
  enabled: true
  defaults:
    sync:
      nodes:
        enabled: true
      services:
        enabled: true
      ingresses:
        enabled: true
