apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: {{name}} # replace with developer/team name
  namespace: default
  labels:
    owner: {{name}}
spec:
  templateRef:
    name: default
    namespace: default
  parameters:
    values: |
      syncer:
        resources: {}
          #limits:
          #  cpu: "500m"
          #  memory: "512Mi"
      ingress:
        enabled: true
