apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: cluster-03
  namespace: loft-cluster-03
  labels:
    owner: admin
spec:
  templateRef:
    name: default
    namespace: default
  parameters:
    values: |
      syncer:
        resources:
          # limits:
          #   cpu: "500m"
          #   memory: "512Mi"
      ingress:
        enabled: true
