apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: developer1
  namespace: default
  labels:
    owner: developer1
spec:
  templateRef:
    name: default
    namespace: default
  parameters:
    values: |
      syncer:
        resources:
          # limits:
          #   cpu: "500m"
          #   memory: "512Mi"
      ingress:
        enabled: true
